// **********************************************************************
//
// Copyright (c) 2003-2011 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.4.2
//
// <auto-generated>
//
// Generated from file `Maxima.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <Maxima.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 304
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 2
#       error Ice patch level mismatch!
#   endif
#endif

static const ::std::string __MaximaLib__MaximaWorker__calculate_name = "calculate";

static const ::std::string __MaximaLib__MaximaDispatcher__registerWorker_name = "registerWorker";

static const ::std::string __MaximaLib__MaximaDispatcher__unregisterWorker_name = "unregisterWorker";

static const ::std::string __MaximaLib__MaximaDispatcher__calculate_name = "calculate";

::Ice::Object* IceInternal::upCast(::MaximaLib::MaximaWorker* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::MaximaLib::MaximaWorker* p) { return p; }

::Ice::Object* IceInternal::upCast(::MaximaLib::MaximaDispatcher* p) { return p; }
::IceProxy::Ice::Object* IceInternal::upCast(::IceProxy::MaximaLib::MaximaDispatcher* p) { return p; }

void
MaximaLib::__read(::IceInternal::BasicStream* __is, ::MaximaLib::MaximaWorkerPrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::MaximaLib::MaximaWorker;
        v->__copyFrom(proxy);
    }
}

void
MaximaLib::__read(::IceInternal::BasicStream* __is, ::MaximaLib::MaximaDispatcherPrx& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::MaximaLib::MaximaDispatcher;
        v->__copyFrom(proxy);
    }
}

::std::string
IceProxy::MaximaLib::MaximaWorker::calculate(const ::std::string& s, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__MaximaLib__MaximaWorker__calculate_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::MaximaLib::MaximaWorker* __del = dynamic_cast< ::IceDelegate::MaximaLib::MaximaWorker*>(__delBase.get());
            return __del->calculate(s, __ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::MaximaLib::MaximaWorker::begin_calculate(const ::std::string& s, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__MaximaLib__MaximaWorker__calculate_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __MaximaLib__MaximaWorker__calculate_name, __del, __cookie);
    try
    {
        __result->__prepare(__MaximaLib__MaximaWorker__calculate_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(s);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::std::string
IceProxy::MaximaLib::MaximaWorker::end_calculate(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __MaximaLib__MaximaWorker__calculate_name);
    ::std::string __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    __is->read(__ret);
    __is->endReadEncaps();
    return __ret;
}

const ::std::string&
IceProxy::MaximaLib::MaximaWorker::ice_staticId()
{
    return ::MaximaLib::MaximaWorker::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::MaximaLib::MaximaWorker::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::MaximaLib::MaximaWorker);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::MaximaLib::MaximaWorker::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::MaximaLib::MaximaWorker);
}

::IceProxy::Ice::Object*
IceProxy::MaximaLib::MaximaWorker::__newInstance() const
{
    return new MaximaWorker;
}

void
IceProxy::MaximaLib::MaximaDispatcher::registerWorker(const ::MaximaLib::MaximaWorkerPrx& worker, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::MaximaLib::MaximaDispatcher* __del = dynamic_cast< ::IceDelegate::MaximaLib::MaximaDispatcher*>(__delBase.get());
            __del->registerWorker(worker, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::MaximaLib::MaximaDispatcher::begin_registerWorker(const ::MaximaLib::MaximaWorkerPrx& worker, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __MaximaLib__MaximaDispatcher__registerWorker_name, __del, __cookie);
    try
    {
        __result->__prepare(__MaximaLib__MaximaDispatcher__registerWorker_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(::Ice::ObjectPrx(::IceInternal::upCast(worker.get())));
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::MaximaLib::MaximaDispatcher::end_registerWorker(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __MaximaLib__MaximaDispatcher__registerWorker_name);
}

void
IceProxy::MaximaLib::MaximaDispatcher::unregisterWorker(const ::MaximaLib::MaximaWorkerPrx& worker, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::MaximaLib::MaximaDispatcher* __del = dynamic_cast< ::IceDelegate::MaximaLib::MaximaDispatcher*>(__delBase.get());
            __del->unregisterWorker(worker, __ctx);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::MaximaLib::MaximaDispatcher::begin_unregisterWorker(const ::MaximaLib::MaximaWorkerPrx& worker, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __MaximaLib__MaximaDispatcher__unregisterWorker_name, __del, __cookie);
    try
    {
        __result->__prepare(__MaximaLib__MaximaDispatcher__unregisterWorker_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(::Ice::ObjectPrx(::IceInternal::upCast(worker.get())));
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::MaximaLib::MaximaDispatcher::end_unregisterWorker(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __MaximaLib__MaximaDispatcher__unregisterWorker_name);
}

::std::string
IceProxy::MaximaLib::MaximaDispatcher::calculate(const ::std::string& s, const ::Ice::Context* __ctx)
{
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__MaximaLib__MaximaDispatcher__calculate_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::MaximaLib::MaximaDispatcher* __del = dynamic_cast< ::IceDelegate::MaximaLib::MaximaDispatcher*>(__delBase.get());
            return __del->calculate(s, __ctx);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::MaximaLib::MaximaDispatcher::begin_calculate(const ::std::string& s, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__MaximaLib__MaximaDispatcher__calculate_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __MaximaLib__MaximaDispatcher__calculate_name, __del, __cookie);
    try
    {
        __result->__prepare(__MaximaLib__MaximaDispatcher__calculate_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__getOs();
        __os->write(s);
        __os->endWriteEncaps();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

::std::string
IceProxy::MaximaLib::MaximaDispatcher::end_calculate(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __MaximaLib__MaximaDispatcher__calculate_name);
    ::std::string __ret;
    if(!__result->__wait())
    {
        try
        {
            __result->__throwUserException();
        }
        catch(const ::Ice::UserException& __ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
        }
    }
    ::IceInternal::BasicStream* __is = __result->__getIs();
    __is->startReadEncaps();
    __is->read(__ret);
    __is->endReadEncaps();
    return __ret;
}

const ::std::string&
IceProxy::MaximaLib::MaximaDispatcher::ice_staticId()
{
    return ::MaximaLib::MaximaDispatcher::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::MaximaLib::MaximaDispatcher::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::MaximaLib::MaximaDispatcher);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::MaximaLib::MaximaDispatcher::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::MaximaLib::MaximaDispatcher);
}

::IceProxy::Ice::Object*
IceProxy::MaximaLib::MaximaDispatcher::__newInstance() const
{
    return new MaximaDispatcher;
}

::std::string
IceDelegateM::MaximaLib::MaximaWorker::calculate(const ::std::string& s, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __MaximaLib__MaximaWorker__calculate_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(s);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::std::string __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        __is->read(__ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateM::MaximaLib::MaximaDispatcher::registerWorker(const ::MaximaLib::MaximaWorkerPrx& worker, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __MaximaLib__MaximaDispatcher__registerWorker_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(::Ice::ObjectPrx(::IceInternal::upCast(worker.get())));
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(!__og.is()->b.empty())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.is()->skipEmptyEncaps();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::MaximaLib::MaximaDispatcher::unregisterWorker(const ::MaximaLib::MaximaWorkerPrx& worker, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __MaximaLib__MaximaDispatcher__unregisterWorker_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(::Ice::ObjectPrx(::IceInternal::upCast(worker.get())));
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(!__og.is()->b.empty())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.is()->skipEmptyEncaps();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

::std::string
IceDelegateM::MaximaLib::MaximaDispatcher::calculate(const ::std::string& s, const ::Ice::Context* __context)
{
    ::IceInternal::Outgoing __og(__handler.get(), __MaximaLib__MaximaDispatcher__calculate_name, ::Ice::Normal, __context);
    try
    {
        ::IceInternal::BasicStream* __os = __og.os();
        __os->write(s);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    ::std::string __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.is();
        __is->startReadEncaps();
        __is->read(__ret);
        __is->endReadEncaps();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

::std::string
IceDelegateD::MaximaLib::MaximaWorker::calculate(const ::std::string& s, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::std::string& __result, const ::std::string& s, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_s(s)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::MaximaLib::MaximaWorker* servant = dynamic_cast< ::MaximaLib::MaximaWorker*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->calculate(_m_s, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::std::string& _result;
        const ::std::string& _m_s;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __MaximaLib__MaximaWorker__calculate_name, ::Ice::Normal, __context);
    ::std::string __result;
    try
    {
        _DirectI __direct(__result, s, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

void
IceDelegateD::MaximaLib::MaximaDispatcher::registerWorker(const ::MaximaLib::MaximaWorkerPrx& worker, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::MaximaLib::MaximaWorkerPrx& worker, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_worker(worker)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::MaximaLib::MaximaDispatcher* servant = dynamic_cast< ::MaximaLib::MaximaDispatcher*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->registerWorker(_m_worker, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::MaximaLib::MaximaWorkerPrx& _m_worker;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __MaximaLib__MaximaDispatcher__registerWorker_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(worker, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::MaximaLib::MaximaDispatcher::unregisterWorker(const ::MaximaLib::MaximaWorkerPrx& worker, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::MaximaLib::MaximaWorkerPrx& worker, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_worker(worker)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::MaximaLib::MaximaDispatcher* servant = dynamic_cast< ::MaximaLib::MaximaDispatcher*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->unregisterWorker(_m_worker, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::MaximaLib::MaximaWorkerPrx& _m_worker;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __MaximaLib__MaximaDispatcher__unregisterWorker_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(worker, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

::std::string
IceDelegateD::MaximaLib::MaximaDispatcher::calculate(const ::std::string& s, const ::Ice::Context* __context)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::std::string& __result, const ::std::string& s, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result),
            _m_s(s)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::MaximaLib::MaximaDispatcher* servant = dynamic_cast< ::MaximaLib::MaximaDispatcher*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->calculate(_m_s, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::std::string& _result;
        const ::std::string& _m_s;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __MaximaLib__MaximaDispatcher__calculate_name, ::Ice::Normal, __context);
    ::std::string __result;
    try
    {
        _DirectI __direct(__result, s, __current);
        try
        {
            __direct.servant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::ObjectPtr
MaximaLib::MaximaWorker::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __MaximaLib__MaximaWorker_ids[2] =
{
    "::Ice::Object",
    "::MaximaLib::MaximaWorker"
};

bool
MaximaLib::MaximaWorker::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__MaximaLib__MaximaWorker_ids, __MaximaLib__MaximaWorker_ids + 2, _s);
}

::std::vector< ::std::string>
MaximaLib::MaximaWorker::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__MaximaLib__MaximaWorker_ids[0], &__MaximaLib__MaximaWorker_ids[2]);
}

const ::std::string&
MaximaLib::MaximaWorker::ice_id(const ::Ice::Current&) const
{
    return __MaximaLib__MaximaWorker_ids[1];
}

const ::std::string&
MaximaLib::MaximaWorker::ice_staticId()
{
    return __MaximaLib__MaximaWorker_ids[1];
}

::Ice::DispatchStatus
MaximaLib::MaximaWorker::___calculate(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::std::string s;
    __is->read(s);
    __is->endReadEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    ::std::string __ret = calculate(s, __current);
    __os->write(__ret);
    return ::Ice::DispatchOK;
}

static ::std::string __MaximaLib__MaximaWorker_all[] =
{
    "calculate",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping"
};

::Ice::DispatchStatus
MaximaLib::MaximaWorker::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__MaximaLib__MaximaWorker_all, __MaximaLib__MaximaWorker_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __MaximaLib__MaximaWorker_all)
    {
        case 0:
        {
            return ___calculate(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
MaximaLib::MaximaWorker::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
MaximaLib::MaximaWorker::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
MaximaLib::MaximaWorker::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type MaximaLib::MaximaWorker was not generated with stream support";
    throw ex;
}

void
MaximaLib::MaximaWorker::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type MaximaLib::MaximaWorker was not generated with stream support";
    throw ex;
}
#endif

void 
MaximaLib::__patch__MaximaWorkerPtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::MaximaLib::MaximaWorkerPtr* p = static_cast< ::MaximaLib::MaximaWorkerPtr*>(__addr);
    assert(p);
    *p = ::MaximaLib::MaximaWorkerPtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::MaximaLib::MaximaWorker::ice_staticId(), v->ice_id());
    }
}

::Ice::ObjectPtr
MaximaLib::MaximaDispatcher::ice_clone() const
{
    throw ::Ice::CloneNotImplementedException(__FILE__, __LINE__);
    return 0; // to avoid a warning with some compilers
}

static const ::std::string __MaximaLib__MaximaDispatcher_ids[2] =
{
    "::Ice::Object",
    "::MaximaLib::MaximaDispatcher"
};

bool
MaximaLib::MaximaDispatcher::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__MaximaLib__MaximaDispatcher_ids, __MaximaLib__MaximaDispatcher_ids + 2, _s);
}

::std::vector< ::std::string>
MaximaLib::MaximaDispatcher::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__MaximaLib__MaximaDispatcher_ids[0], &__MaximaLib__MaximaDispatcher_ids[2]);
}

const ::std::string&
MaximaLib::MaximaDispatcher::ice_id(const ::Ice::Current&) const
{
    return __MaximaLib__MaximaDispatcher_ids[1];
}

const ::std::string&
MaximaLib::MaximaDispatcher::ice_staticId()
{
    return __MaximaLib__MaximaDispatcher_ids[1];
}

::Ice::DispatchStatus
MaximaLib::MaximaDispatcher::___registerWorker(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::MaximaLib::MaximaWorkerPrx worker;
    ::MaximaLib::__read(__is, worker);
    __is->endReadEncaps();
    registerWorker(worker, __current);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
MaximaLib::MaximaDispatcher::___unregisterWorker(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::MaximaLib::MaximaWorkerPrx worker;
    ::MaximaLib::__read(__is, worker);
    __is->endReadEncaps();
    unregisterWorker(worker, __current);
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
MaximaLib::MaximaDispatcher::___calculate(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.is();
    __is->startReadEncaps();
    ::std::string s;
    __is->read(s);
    __is->endReadEncaps();
    ::IceInternal::BasicStream* __os = __inS.os();
    ::std::string __ret = calculate(s, __current);
    __os->write(__ret);
    return ::Ice::DispatchOK;
}

static ::std::string __MaximaLib__MaximaDispatcher_all[] =
{
    "calculate",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "registerWorker",
    "unregisterWorker"
};

::Ice::DispatchStatus
MaximaLib::MaximaDispatcher::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< ::std::string*, ::std::string*> r = ::std::equal_range(__MaximaLib__MaximaDispatcher_all, __MaximaLib__MaximaDispatcher_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __MaximaLib__MaximaDispatcher_all)
    {
        case 0:
        {
            return ___calculate(in, current);
        }
        case 1:
        {
            return ___ice_id(in, current);
        }
        case 2:
        {
            return ___ice_ids(in, current);
        }
        case 3:
        {
            return ___ice_isA(in, current);
        }
        case 4:
        {
            return ___ice_ping(in, current);
        }
        case 5:
        {
            return ___registerWorker(in, current);
        }
        case 6:
        {
            return ___unregisterWorker(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
MaximaLib::MaximaDispatcher::__write(::IceInternal::BasicStream* __os) const
{
    __os->writeTypeId(ice_staticId());
    __os->startWriteSlice();
    __os->endWriteSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__write(__os);
#else
    ::Ice::Object::__write(__os);
#endif
}

void
MaximaLib::MaximaDispatcher::__read(::IceInternal::BasicStream* __is, bool __rid)
{
    if(__rid)
    {
        ::std::string myId;
        __is->readTypeId(myId);
    }
    __is->startReadSlice();
    __is->endReadSlice();
#if defined(_MSC_VER) && (_MSC_VER < 1300) // VC++ 6 compiler bug
    Object::__read(__is, true);
#else
    ::Ice::Object::__read(__is, true);
#endif
}

// COMPILERFIX: Stream API is not supported with VC++ 6
#if !defined(_MSC_VER) || (_MSC_VER >= 1300)
void
MaximaLib::MaximaDispatcher::__write(const ::Ice::OutputStreamPtr&) const
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type MaximaLib::MaximaDispatcher was not generated with stream support";
    throw ex;
}

void
MaximaLib::MaximaDispatcher::__read(const ::Ice::InputStreamPtr&, bool)
{
    Ice::MarshalException ex(__FILE__, __LINE__);
    ex.reason = "type MaximaLib::MaximaDispatcher was not generated with stream support";
    throw ex;
}
#endif

void 
MaximaLib::__patch__MaximaDispatcherPtr(void* __addr, ::Ice::ObjectPtr& v)
{
    ::MaximaLib::MaximaDispatcherPtr* p = static_cast< ::MaximaLib::MaximaDispatcherPtr*>(__addr);
    assert(p);
    *p = ::MaximaLib::MaximaDispatcherPtr::dynamicCast(v);
    if(v && !*p)
    {
        IceInternal::Ex::throwUOE(::MaximaLib::MaximaDispatcher::ice_staticId(), v->ice_id());
    }
}
